language: node_js
node_js:
 - "node"
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  local-dir: ./dist
  email: javieryep@gmail.com
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master